version: "3.8"
services:
  app:
    build: ./
    command: ./wait-for-postgres.sh db ./app
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - postgres
    environment:
      - DB_PASSWORD="${DB_PASSWORD}"
      - STORAGE_TYPE="${STORAGE_TYPE}"

  postgres:
    image: postgres:latest
    env_file:
      - .env
    volumes:
    - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - DB_PASSWORD="${DB_PASSWORD}"
    ports:
      - "5432:5432"
    restart: always